# Linear Algebra with Numpy

Numpy is a powerful, open source library in Python that can be used for a variety of linear algebra tasks. It can be installed via the command line with the following command:

```sh
pip install numpy
```

Once Numpy is installed, it can be imported in Python as follows. To make a matrix or *numpy array*, we can create it from lists representing rows. Other data structures can be turned into numpy arrays using this command as well. Some attributes of the array are shown. These include the rows and columns (*shape*), number of dimensions (*ndim*), transpose (*T*) along with the matrix itself.

In [20]:
import numpy as np

X = np.array([[1, 3, 2, 5], [4, 2, 2, 1], [6, 5, 1, 3]])

print(X)
print(X.shape)
print(X.ndim)
print(X.T)

[[1 3 2 5]
 [4 2 2 1]
 [6 5 1 3]]
(3, 4)
2
[[1 4 6]
 [3 2 5]
 [2 2 1]
 [5 1 3]]


In [2]:
#linspace makes equal divisions from a start to end point
A = np.linspace(0, 1, 5)
print(A)

[0.   0.25 0.5  0.75 1.  ]


In [3]:
#makes diagonal matrices
B = np.diag(np.array([1,2,3,4]))
print(B)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [4]:
#random numbers from uniform dist
C = np.random.rand(4)
print(C)

[0.60805265 0.06967698 0.79379412 0.31224288]


In [5]:
#random numbers from normal dist
D = np.random.randn(4)
print(D)

[ 0.00622999 -0.44102127 -3.04464332 -0.22858529]


In [7]:
E = np.random.randn(4)
Y = np.array([C, D, E])

print(Y.T.dot(X)) #matrix multiplication

[[  8.02409067   7.99588299   2.46041829   6.74205228]
 [ -7.55420173  -5.55617296  -1.71932086  -3.02253319]
 [-10.81817209  -3.23573173  -4.4072639    1.2076308 ]
 [ 12.34396642  11.2679453    2.32499263   7.80566145]]


In [8]:
print(X.sum(axis=0)) #col sums
print(X.sum(axis=1)) #row sums
print(X.sum()) #total sum

[11 10  5  9]
[11  9 15]
35


In [18]:
print(np.amin(X, axis = 0))
print(np.amax(X, axis = 0))
print(np.argmin(X, axis = 0))
print(np.argmax(X, axis = 0))
print(np.mean(X, axis = 0))
print(np.std(X, axis = 0))

[1 2 1 1]
[6 5 2 5]
[0 1 2 1]
[2 2 0 0]
[3.66666667 3.33333333 1.66666667 3.        ]
[2.05480467 1.24721913 0.47140452 1.63299316]
